# Description:
#   Carlton & More Celebration
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   dance - Display a dancing Carlton
#
# Author:
#   pingles
#   http://www.funnyordie.com/lists/1d2da3358d/the-best-dancing-gifs

carltons = [
	"http://media.tumblr.com/tumblr_lrzrlymUZA1qbliwr.gif",
	"http://3deadmonkeys.com/gallery3/var/albums/random_stuff/Carlton-Dance-GIF.gif",
	"http://gifsoup.com/webroot/animatedgifs/987761_o.gif",
	"http://gifsoup.com/view1/1307943/carlton-banks-dance-o.gif",
	"http://s2.favim.com/orig/28/carlton-banks-dance-Favim.com-239179.gif",
	"http://gifsoup.com/webroot/animatedgifs/131815_o.gif",
	"http://media.tumblr.com/tumblr_lrzrlymUZA1qbliwr.gif",
	"http://3deadmonkeys.com/gallery3/var/albums/random_stuff/Carlton-Dance-GIF.gif",
	"http://i.imgur.com/Mt39r.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/1162345_o.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/152765_o.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/163563561.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/1tumblr_lgp6q5NhE21qcjtu8o1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/1zl92fn.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/23ma42w.jpg.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/280sw007883.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/30075yu908.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/300sw047yusw9.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/AD-Dance.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/adriansito.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/bale1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/bale2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/beyonce1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/beyonce2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/boratgroupdance5is.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/danc.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/dd1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/dd2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash3.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash4.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash5.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash6.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash7.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/flash8.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/freaks.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/gary.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/giffed-hitler06.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/james2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/james3.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/kanye%201.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/kanye%202.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/kanye3.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/pr1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/pr2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sax.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sbtb2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sbtb3.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sbtb4.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/smang3vfqo.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/smith1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/smith2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/smith3.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/smith4.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny1a.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny2.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny2a.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny3.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny4.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny5.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sunny6.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/sytycd-gif1.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_l0p4mt0QAa1qa7q08o1_400.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_l51nsfJN331qzxf8vo1_400.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_l7qse5wJZ31qaqggd.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_l95zexMVU51qzdf0go1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_l9lkbpRkXT1qb9fdoo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lfa5tmS93q1qdok1go1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lgl6p1nOeU1qazkdco1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lgqwpt5PfZ1qfjmnk.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lgqwsbEa891qfjmnk.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lgslykEox31qdp3rbo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lh5637fCg51qzcik8o1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lhgebyZ7781qzaxefo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lhjxn17LeK1qdy7bo.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lhkbbp0VCL1qho7avo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lhpckhQ2mO1qamwa1o1_400.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lhrzztdSKy1qb7hapo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lhzn7g4p9n1qcnhhzo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_li6dilTTe21qc4qzm.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lic7zaNNkQ1qabm5vo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_likmsbsY0M1qgt3ngo1_500%202.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lildlrNEye1qgns73%202.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lit5wdB6j21qcfba3o1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_liuqmpbAG81qzb2ai.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lj3t79ToKm1qchk28.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_ljhxqfJwB71qhisruo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_ljmilvvrED1qirhr3o1_250.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_ljnfjqU7mB1qbzahao1_400.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lk54oh7tTt1qeot64.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lkbxc4qncE1qd2avdo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_lkxuj020kv1qensgg.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_ll3jgmsPho1qzbiyjo1_500.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_llatanJkKU1qbnthu.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_llatbbCeky1qbnthu.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/tumblr_llax2rbRRS1qg87cc.gif",
	"http://assets0.ordienetworks.com/images/GifGuide/dancing/Van%20Halen%20with%20David%20Lee%20Roth%20is%20like%20all%20the%20best%20parts%20of%20snorting%20coke%20off%20a%20stripper%E2%80%99s%20ass..gif"
]

module.exports = (robot) ->
  robot.hear /\b(dance|happy)\b/i, (msg) ->
    msg.send msg.random carltons